### ISSUE TITLE
Issues already raised at emojione repo

### ISSUE THREAD

**Issue by Crissov** [Ranks/emojione-assets#1]
Should we re-raise Artwork issues already opened at the [Emojione code repository](https://github.com/Ranks/emojione/)? Will/can they be moved here?

**Comment by kevinranks** [comment]
Hey @Crissov! 

Once we are finished launching 3.0 we will need to do an audit of the issue log and move over any issues that still stand. If you would like to help in that process, we won't complain 😄 . 

Keep in mind that 3.0 brings completely new artwork and we really only want issues opened for things that are obvious mistakes in the artwork.

**Comment by Crissov** [comment]
For now, I have gone through the issues I had raised myself.
